#!/bin/bash

# Chek if current path is a git repo
git rev-parse --is-inside-work-tree 1> /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "There is no git repository in the current path."
  exit
fi

# Check if a branch name was given, otherwise ask for one
if [ -z "$1" ]; then
  current=$(git rev-parse --abbrev-ref HEAD)
  options=$(git branch --format="%(refname:short)") 

  # remove current branch from options
  options=( "${options[@]/$current/}" )
  if [[ -z $options ]]; then
    echo "There are no other branch to switch to."
    exit
  fi

  branch=$(gum filter $options)
else
  branch=$1
fi

if [ -z "${branch}" ]; then
  echo "No branch was selected."		
  exit
fi

git switch "$branch"
